version: "3.8"

services:

    yarn:
        image: node
        volumes:
            - .:/opt/briefly
        working_dir: /opt/briefly
        networks:
            - default
        ports:
            - 80:80
        entrypoint: yarn
